services:
  db:
    image: sujanadh/postgis-pgaudit-16-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data/

  backend:
    build: .
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db

  

volumes:
  fastapi_postgres_data:
  data: